name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day at midnight
  workflow_dispatch: # Allows running manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: sundrabomjan
          outputs: |
            ./assets/github-snake.svg

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ğŸ Update Snake Animation"
